version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - sqlite-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=MySuperSecretKeyForJWT2025ThatIsLongEnough256Bits!
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "4200:80"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqlite-data:


networks:
  app-network:
    driver: bridge
