import { WeatherInterpretationCode } from '../../models/weather.model';
import { FavoriteCity } from './home.models';

export const MOCK_FAVORITE_CITIES: FavoriteCity[] = [
  {
    name: 'Ensoleille',
    country: 'Theme: Ciel degage',
    temperature: 28,
    icon: 'icon-sun',
    condition: 'Ciel degage',
    humidity: 45,
    wind: 8,
    cloudCover: 5,
    pressure: 1020,
    lastUpdate: '2 min',
    weatherCode: WeatherInterpretationCode.ClearSky,
    coords: { lat: 43.710173, lon: 7.261954 },
    source: 'mock'
  },
  {
    name: 'Nuageux',
    country: 'Theme: Partiellement nuageux',
    temperature: 22,
    icon: 'icon-partly-cloudy',
    condition: 'Partiellement nuageux',
    humidity: 60,
    wind: 12,
    cloudCover: 55,
    pressure: 1015,
    lastUpdate: '5 min',
    weatherCode: WeatherInterpretationCode.MainlyClear,
    coords: { lat: 50.62925, lon: 3.057256 },
    source: 'mock'
  },
  {
    name: 'Brouillard',
    country: 'Theme: Brouillard',
    temperature: 15,
    icon: 'icon-fog',
    condition: 'Brouillard epais',
    humidity: 90,
    wind: 5,
    cloudCover: 80,
    pressure: 1012,
    lastUpdate: '8 min',
    weatherCode: WeatherInterpretationCode.Fog,
    coords: { lat: 45.764043, lon: 4.835659 },
    source: 'mock'
  },
  {
    name: 'Bruine',
    country: 'Theme: Bruine',
    temperature: 16,
    icon: 'icon-drizzle',
    condition: 'Bruine legere',
    humidity: 80,
    wind: 18,
    cloudCover: 85,
    pressure: 1008,
    lastUpdate: '4 min',
    weatherCode: WeatherInterpretationCode.Drizzle,
    coords: { lat: 47.218371, lon: -1.553621 },
    source: 'mock'
  },
  {
    name: 'Pluvieux',
    country: 'Theme: Pluie',
    temperature: 12,
    icon: 'icon-rain',
    condition: 'Pluie moderee',
    humidity: 85,
    wind: 22,
    cloudCover: 92,
    pressure: 1005,
    lastUpdate: '3 min',
    weatherCode: WeatherInterpretationCode.Rain,
    coords: { lat: 48.390394, lon: -4.486076 },
    source: 'mock'
  },
  {
    name: 'Neige',
    country: 'Theme: Neige',
    temperature: -2,
    icon: 'icon-snow',
    condition: 'Chutes de neige',
    humidity: 75,
    wind: 15,
    cloudCover: 88,
    pressure: 1010,
    lastUpdate: '6 min',
    weatherCode: WeatherInterpretationCode.Snow,
    coords: { lat: 45.923698, lon: 6.869434 },
    source: 'mock'
  },
  {
    name: 'Orageux',
    country: 'Theme: Orage',
    temperature: 18,
    icon: 'icon-thunderstorm',
    condition: 'Orage violent',
    humidity: 88,
    wind: 35,
    cloudCover: 96,
    pressure: 998,
    lastUpdate: '1 min',
    weatherCode: WeatherInterpretationCode.Thunderstorm,
    coords: { lat: 43.604652, lon: 1.444209 },
    source: 'mock'
  }
];
